# Dependencies
# auto: 			  true
markdown:         redcarpet
#pygments:         true
highlighter:        rouge

# Permalinks
permalink:        pretty

# Setup
title:            Dimitris Paxinos
tagline:          Under Construction
# url:              http://getpoole.com
paginate:         1
baseurl:          /
# author:
  # name:           Mark Otto
  # url:            https://twitter.com/mdo
  # email:          markdotto@gmail.com

# Custom vars
# version:          1.0.0
# github:
  # repo:           https://github.com/poole/poole
  
# avatar: http://www.wpclipart.com/medical/symbols/medical_symbols_2/eye.png  

encoding: utf-8

pages_list:      
  About: '/aboutme'   
  Archive: '/archive'
  Tags: '/tags'

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"