# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Dimitris Paxinos
tagline:          For testing Purposes
url:              http://getpoole.com
paginate:         1
baseurl:          /
author:
  name:           Mark Otto
  url:            https://twitter.com/mdo
  email:          markdotto@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/poole/poole
  
avatar: http://www.wpclipart.com/medical/symbols/medical_symbols_2/eye.png  

pages_list:         
  Archive: '/archive'
